# Generated by Django 4.1.2 on 2022-10-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
